### ISSUE TITLE
rq4d.go missing

### ISSUE THREAD

**Issue by wannaknowmo** [julianfrank/rq4d#1]
hi Julian,

seems like rq4d.go is missing, i'm currently using a newer version of rqlited than the one that you you in your example.
let me know if you need more info.

here is my dockerfile

Step 1 : FROM golang:latest
—> 9850763835e0
Step 2 : ADD . /usr/local/bin
—> Using cache
—> 3fc4158fa469
Step 3 : WORKDIR /usr/local/bin
—> Using cache
—> 2a70051bbb1a
Step 4 : COPY /rqlited-v3.9.0-linux-amd64.tar.gz /usr/local/bin
—> Using cache
—> 662ec3955953
Step 5 : RUN tar xvfz rqlited-v3.9.0-linux-amd64.tar.gz
—> Using cache
—> 45f3095debce
Step 6 : RUN mv rqlited-v3.9.0-linux-amd64 rqlite
—> Using cache
—> aba3a2e0cc9f
Step 7 : ADD / /go/src
—> Using cache
—> 5687bec72246
Step 8 : RUN go build /go/src/rq4d.go
—> Running in af8259ac4870
stat /go/src/rq4d.go: no such file or directory
The command ‘go build /go/src/rq4d.go’ returned a non-zero code: 1

**Comment by julianfrank** [comment]
rookie mistake... but now corrected...Simple...The main.go had to be renamed to rq4d ... Clone the current version and it will work...

**Comment by wannaknowmo** [comment]
thank you i will try it.
