### ISSUE TITLE
RDB no such host

### ISSUE THREAD

**Issue by wannaknowmo** [julianfrank/rq4d#2]
getting the following when i try to run the container

root@toto ~]# docker run -it rq4d  
2017/01/10 19:03:30 Error during DNS Host lookup -> lookup rdb on xx.xxx.xx.xx:53: no such host

alex

**Comment by julianfrank** [comment]
The default Docker Engine called using 'docker' only creates the container and runs it but does not provide any service discovery and scaling mechanism...This is why you see the 'no such host' error....when running the container without using docker-compose

rq4d is a wrapper Orchestration tools like Docker-Compose which use DNS for Service Discovery...specifically tweaked for rqlite application

Install Docker-Compose and then use docker-compose up --build -d rdb to get the first instance running under service name 'rdb'...You can scale multiple instances with the command given in the readme...Do let me know if this worked

**Comment by julianfrank** [comment]
Closing this issue

**Comment by wannaknowmo** [comment]
looks good sorry about that.
i don't have access to github from docker swarm cluster.

thanks again

**Comment by julianfrank** [comment]
Pls don't apologise...we are all learning...four months ago I was confused in exactly this point 😊...
Thanks for trying...hope it helps in your projects

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 19, 2017 at 3:03 AM, wannaknowmo<notifications@github.com> wrote:   
looks good sorry about that.
i don't have access to github from docker swarm cluster.

thanks again
